-- Full PineTrack Supabase schema setup.
-- Run this script in Supabase SQL editor to create all tables required by the backend.

-- 1. Users
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'worker',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Plots
CREATE TABLE IF NOT EXISTS public.plots (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    area_ha FLOAT,
    crop_type TEXT DEFAULT 'Pineapple',
    planting_date TIMESTAMPTZ,
    growth_stage TEXT,
    status TEXT DEFAULT 'Proceed',
    health_score FLOAT DEFAULT 0,
    location_x FLOAT,
    location_y FLOAT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Task templates
CREATE TABLE IF NOT EXISTS public.task_templates (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT,
    description TEXT,
    start_offset_days INT,
    end_offset_days INT,
    frequency TEXT,
    interval TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tasks
CREATE TABLE IF NOT EXISTS public.tasks (
    id TEXT PRIMARY KEY,
    plot_id TEXT,
    title TEXT,
    type TEXT,
    task_date TIMESTAMPTZ,
    status TEXT,
    description TEXT,
    original_date TIMESTAMPTZ,
    proposed_date TIMESTAMPTZ,
    reason TEXT,
    buffer_days INT,
    assigned_worker_id TEXT,
    assigned_worker_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Workers
CREATE TABLE IF NOT EXISTS public.workers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    contact TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    tasks_completed INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Threshold config
CREATE TABLE IF NOT EXISTS public.thresholds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature_min FLOAT,
    temperature_max FLOAT,
    soil_moisture_min FLOAT,
    soil_moisture_max FLOAT,
    updated_at TIMESTAMPTZ,
    updated_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Task evaluation thresholds
CREATE TABLE IF NOT EXISTS public.task_eval_thresholds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    soil_moisture_min FLOAT,
    soil_moisture_max FLOAT,
    temperature_min FLOAT,
    temperature_max FLOAT,
    rain_mm_min FLOAT,
    rain_mm_heavy FLOAT,
    waterlogging_hours FLOAT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Raw sensor data
CREATE TABLE IF NOT EXISTS public.raw_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    plot_id TEXT,
    data_added TIMESTAMPTZ DEFAULT NOW(),
    temperature FLOAT,
    soil_moisture FLOAT,
    nitrogen FLOAT
);

-- 9. Cleaned sensor data
CREATE TABLE IF NOT EXISTS public.cleaned_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    plot_id TEXT,
    data_added TIMESTAMPTZ,
    processed_at TIMESTAMPTZ,
    temperature FLOAT,
    soil_moisture FLOAT,
    nitrogen FLOAT,
    cleaned_temperature FLOAT,
    cleaned_soil_moisture FLOAT,
    cleaned_nitrogen FLOAT,
    temperature_qv FLOAT,
    temperature_status TEXT,
    soil_moisture_qv FLOAT,
    soil_moisture_status TEXT,
    nitrogen_qv FLOAT,
    nitrogen_status TEXT
);

-- 10. Predictions
CREATE TABLE IF NOT EXISTS public.predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    plot_id TEXT,
    forecast_time TIMESTAMPTZ,
    temperature FLOAT,
    soil_moisture FLOAT,
    nitrogen FLOAT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Recommendations
CREATE TABLE IF NOT EXISTS public.recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    category TEXT,
    parameter TEXT,
    message TEXT,
    priority INT
);

-- 12. Observations
CREATE TABLE IF NOT EXISTS public.observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plot_id TEXT NOT NULL,
    author TEXT NOT NULL,
    note TEXT NOT NULL,
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
